high_school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("high_school_app.urls", namespace="high_school_app")),
]

high_school_app/urls.py
from django.urls import path
from .views import home, all_streams, one_stream, all_students, one_student, edit_student, delete_student

app_name="high_school_app"

urlpatterns = [
    path('', home, name="home"),
    path('all_streams', all_streams, name="all_streams"),
    path('stream/<id>', one_stream, name='stream'),
    path('all_students', all_students, name="all_students"),
    path('student/<id>', one_student, name='student'),
    path('edit_student/<id>', edit_student, name="edit_student"),
    path('delete_student/<id>', delete_student, name="delete_student"),
]

high_school_app/models.py
from django.db import models

# Create your models here.

class Stream(models.Model):
    stream_name = models.CharField(max_length=50)

    def __str__(self):
        return self.stream_name
    
class Student(models.Model):
    name = models.CharField(max_length=250)
    stream = models.ForeignKey(Stream, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

high_school_app/forms.py
from django import forms 
from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('name', 'stream')
        # exclude = ['stream']

high_school_app/views.py
from django.shortcuts import render, redirect
from .models import Stream, Student
from .forms import StudentForm
# Create your views here.


# Create your views here.
def home(request):
    return render(request, 'home.html')

def all_streams(request):
    streams = Stream.objects.all()
    context = {
        'streams' : streams
    }

    return render(request, 'all_streams.html', context)

def one_stream(request, id):
    one_stream = Stream.objects.get(id=id)
    students = Student.objects.all()

    context = {
        "one_stream" : one_stream,
        "students" : students
    }

    return render(request, "one_stream.html", context)

def all_students(request):
    students = Student.objects.all()
    
    context = {
        'students' : students
    }

    return render(request, "all_students.html", context)

def one_student(request, id):
    one_student = Student.objects.get(id=id)

    context = {
        'one_student': one_student
    }

    return render(request, "one_student.html", context)

def edit_student(request, id):
    student = Student.objects.get(id=id)
    form = StudentForm(request.POST or None, instance=student)
    if form.is_valid():
        form.save()
        return redirect('high_school_app:student', id=student.id)

    context = {
        "form" : form,
        "student": student
    }

    return render(request, 'edit_student.html', context)

def delete_student(request, id):
    student = Student.objects.get(id=id)
    student.delete()
    
    return redirect('high_school_app:all_students')

high_school_app/templates/all_streams.html
<div>
    {% for s in streams %}
        <p>
        <a href="{% url 'high_school_app:stream' id=s.id %}">{{ s.stream_name }}</a>
        </p>

    {% endfor %}
</div>

high_school_app/templates/all_students.html
<div>
    {% for s in students %}
        <p>
            <a href="{% url 'high_school_app:student' id=s.id %}">{{ s.name }}</a>
            <span>{{ s.stream.stream_name }}</span>
        </p>
        <p>

    {% endfor %}
</div>

high_school_app/templates/edit_student.html
<div class="container">
        <div class="row">
            <div class="col-md-4">
                <h3>EDIT PROFILE</h3>
            </div>
            <div class="col-md-8">
               
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <br />
                    <input type="submit" class="btn btn-info" value="Update">
                </form>
        
            </div>
        </div>
    </div>

high_school_app/templates/home.html
<div>
    <h1>KILIMO HIGH SCHOOL</h1>
</div>

<div>
    <p><a href="{% url 'high_school_app:all_streams' %}">View Classes</a></p>
</div>

<div>
    <p><a href="{% url 'high_school_app:all_students' %}">View Students</a></p>
</div>

high_school_app/templates/one_stream.html
    <h1>{{ one_stream.stream_name }}</h1>

    {% for student in students %}
        {% if one_stream == student.stream %}
        <p>
            <a href="{% url 'high_school_app:student' id=student.id %}">{{ student }}</a>
        </p>
        {% endif %}
    {% endfor %}

high_school_app/templates/one_student.html
<div>

    <p>{{ one_student.name }}</p>
    <p>{{ one_student.stream }}</p>
    <a href="{% url 'high_school_app:edit_student' id=one_student.id %}">Edit Student Profile</a>
    <a href="{% url 'high_school_app:delete_student' id=one_student.id %}">Delete Student Profile</a>

</div>